// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Image struct {
	Default   string `json:"default"`
	Featured  string `json:"featured"`
	Thumbnail string `json:"thumbnail"`
	Wide      string `json:"wide"`
}

type Podcast struct {
	ID              string `json:"id"`
	Title           string `json:"title"`
	Images          *Image `json:"images"`
	IsExclusive     bool   `json:"isExclusive"`
	PublisherName   string `json:"publisherName"`
	PublisherID     string `json:"publisherId"`
	MediaType       string `json:"mediaType"`
	Description     string `json:"description"`
	CategoryID      string `json:"categoryId"`
	CategoryName    string `json:"categoryName"`
	HasFreeEpisodes bool   `json:"hasFreeEpisodes"`
	PlaySequence    string `json:"playSequence"`
}
